#!/usr/bin/env lua
--[[ Checklist Specification Language ]]
--[[
            Copyright Ryan Pavlik 2011-2012.
Distributed under the Boost Software License, Version 1.0.
    (See accompanying file LICENSE_1_0.txt or copy at
          http://www.boost.org/LICENSE_1_0.txt)
]]

require "checklists"

for _, v in ipairs(arg) do
	checklists.load(v)
end
checklists.to_markdown()

